cscvrest_homepage:
    path:     /hello/{name}
    defaults: { _controller: CSCVRESTBundle:Default:index }

# 配置Product路由
cscv_rest_products:
    resource: CSCV\Bundle\RESTBundle\Controller\ProductController
    prefix: /api
    type: rest

# 配置Image路由
cscv_rest_images:
    resource: CSCV\Bundle\RESTBundle\Controller\ImageController
    prefix: /api
    type: rest

cscv_rest_image_upload:
    path: /api/images/upload
    defaults: { _controller: CSCVRESTBundle:Image:upload}
    methods: [POST]

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
