cscvrest_homepage:
    path:     /hello/{name}
    defaults: { _controller: CSCVRESTBundle:Default:index }

# 配置Product路由
cscv_rest_products:
    resource: CSCV\Bundle\RESTBundle\Controller\ProductController
    prefix: /api
    type: rest

# 配置Image路由
cscv_rest_images:
    resource: CSCV\Bundle\RESTBundle\Controller\ImageController
    prefix: /api
    type: rest

# 上传图像的路由
cscv_rest_image_upload:
    path: /api/images/upload
    defaults: { _controller: CSCVRESTBundle:Image:upload }
    methods: [POST]

# 配置疾病路由
cscv_rest_diseases:
    resource: CSCV\Bundle\RESTBundle\Controller\DiseaseController
    prefix: /api
    type: rest

# 获得对应疾病的所有图像
cscv_rest_disease_images:
   path: /api/diseaes/{disease}/images
   defaults: { _controller: CSCVRESTBundle:Disease:getImages }
   methods: [GET]

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
