services:
    cscv_storage_bundle.image.form.type:
        class: CSCV\Bundle\StorageBundle\Form\Type\ImageType
        arguments: [@service_container]
        scope: request
        tags:
            - { name: form.type, alias: image }