cscv_app_homepage:
    path:     /
    defaults: { _controller: CSCVAppBundle:Default:index }

# 图像标定主页
cscv_app_image_index:
    path:    /image
    defaults: { _controller: CSCVAppBundle:Image:index }

# 图像上传
cscv_app_image_upload:
    path:   /image/upload
    defaults: { _controller: CSCVAppBundle:Image:upload }
    methods: [POST]

cscv_app_image_file:
    path:   /image/file
    defaults: { _controller: CSCVAppBundle:Image:file }

# 浏览疾病
cscv_app_disease_index:
    path: /disease
    defaults: { _controller: CSCVAppBundle:Disease:index }

# 显示疾病
cscv_app_disease_show:
    path: /disease/show/{id}
    defaults: { _controller: CSCVAppBundle:Disease:show}
    methods: [GET]

# 新建疾病
cscv_app_disease_new:
    path: /disease/new
    defaults: { _controller: CSCVAppBundle:Disease:new}

# 编辑疾病
cscv_app_disease_edit:
    path: /disease/edit/{id}
    defaults: { _controller: CSCVAppBundle:Disease:edit}

# 显示Token
cscv_app_token_index:
    path: /token
    defaults: { _controller: CSCVAppBundle:Token:index }

# 创建Token
cscv_app_token_new:
    path: /token/new
    defaults: { _controller: CSCVAppBundle:Token:new }
    methods: [POST]

# 编辑Token
cscv_app_token_update:
    path: /token/update
    defaults: { _controller: CSCVAppBundle:Token:update }
    methods: [PUT]

# 删除Token
cscv_app_token_remove:
    path: /token/remove
    defaults: { _controller: CSCVAppBundle:Token:remove }
    methods: [DELETE]

