services:
    cscv.twig.asset_if_extension:
        class: CSCV\Bundle\AppBundle\Services\Extension\CustomTwigExtension
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }
